version: "3.9"

services:
  secure-webserver:
    image: hkdigital/nginx-2021a   # docker-hub
    # image: hkdigital-nginx-2021a   # local

    restart: always # "no"|always|on-failure|unless-stopped

    environment:
      - INSTALL_DEFAULTS=secure-webserver

    ports:
      # host-port -> container port
      - "1080:80"
      - "1443:443"

    volumes:
      - ./volumes/config:/mnt/config
      - ./volumes/log:/mnt/log
      - ./volumes/certificates:/mnt/certificates
#       - secure-webserver-webroot:/mnt/webroot
#       - secure-webserver-media:/mnt/media

# volumes:
#   secure-webserver-webroot:
#   secure-webserver-media: