version: "3.9"

services:
  webserver:
    # image: hkdigital/nginx-2021a   # docker-hub
    image: hkdigital-nginx-2021a   # local

    restart: always # "no"|always|on-failure|unless-stopped

    environment:
      - INSTALL_DEFAULTS=webserver

    ports:
      # Let docker choose port numbers on the host
      # - "80"

      # host-port -> container port
      - "1080:80"

    volumes:
      - ./volumes/webroot:/mnt/webroot
      - ./volumes/config:/mnt/config
      - ./volumes/certificates:/mnt/certificates
      - ./volumes/log:/mnt/log
      - ./volumes/media:/mnt/media

    # volumes:
    #   - webserver-webroot:/mnt/webroot
    #   - webserver-config:/mnt/config
    #   - webserver-certificates:/mnt/certificates
    #   - webserver-log:/mnt/log
    #   - webserver-media:/mnt/media

# volumes:
#   webserver-webroot:
#   webserver-certificates:
#   webserver-config:
#   webserver-log:
#   webserver-media:
