version: "3.9"

services:

  # .............................................................. ingress proxy

  ingress-proxy-http:
    image: hkdigital/nginx-2021a   # docker-hub
    # image: hkdigital-nginx-2021a   # local

    restart: always # "no"|always|on-failure|unless-stopped

    depends_on:
      - webserver

    environment:
      - INSTALL_DEFAULTS=ingress-proxy

    ports:
      # host-port:internal-port
      - "11080:80"

    volumes:
      - ./volumes/config:/mnt/config
      - ./volumes/log:/mnt/log

  # .................................................................. webserver

  webserver:
    image: hkdigital-nginx-2021a

    restart: always # "no"|always|on-failure|unless-stopped

    # @note not exposing ports - only using internal ports

    volumes:
      - ./volumes/webroot:/mnt/webroot
